# This is a basic workflow to help you get started with Actions

name: TweakBuild

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: theos env
        run: |
          export THEOS=/opt/theos
          sudo mkdir -p $THEOS
          brew install dpkg ldid
          sudo git clone --recursive git://github.com/theos/theos.git $THEOS
          sudo rm -rf $THEOS/sdks/
          sudo git clone https://github.com/EvanDbg/XcodeDefaultOb.git ../XcodeDefaultOb
          pwd
          ls -la
          pwd
          sudo mkdir -p $THEOS/sdks/iPhoneOS14.4.sdk
          sudo cp -r ../XcodeDefaultOb/iPhoneOS14.4.sdk/* $THEOS/sdks/iPhoneOS14.4.sdk/
          sudo cp ../XcodeDefaultOb/Prefix.pch $THEOS/Prefix.pch
          sudo cp ../XcodeDefaultOb/RemoteLog.h $THEOS/include
          make clean package FINALPACKAGE=1
          
      - name: Automatic Releases
        # You may pin to the exact commit or the version.
        # uses: marvinpinto/action-automatic-releases@526ce12c6675bbe6e0e9a4169c90d09a3f7ad3e2
        uses: marvinpinto/action-automatic-releases@v1.2.0
        with:
          # GitHub secret token
          repo_token: ${{ secrets.G_TOKEN }}
          automatic_release_tag: 1.0.0
          prerelease: false
          # Assets to upload to the release
          files: ./packages/*.deb
